# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Maven in Dev

on:
  pull_request:
    branches: [ master,develop ]

jobs:
  build:

    runs-on: macrunner

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: |
        run_id=${{ github.run_id }}
        export M2_HOME="/Users/thi/Downloads/apache-maven-3.9.2"
        PATH="${M2_HOME}/bin:${PATH}"
        export PATH
        sed -i "" "s|github_run_id|$run_id|" src/main/webapp/index.jsp
        mvn test
        mvn package
        ls -ll
        scp target/maven-web.war ubuntu@46.137.192.81:/opt/wildfly/standalone/deployments
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
